<HTML>
<HEAD>
    <META CHARSET="UTF-8">
    <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0">
    <META HTTP-EQUIV="X-UA-COMPATIBLE" CONTENT="IE=EDGE">
    <TITLE>WEB COMPRAS</TITLE>
    <LINK REL="STYLESHEET" HREF="BOOTSTRAP.MIN.CSS">
</HEAD>

<BODY>
<H1>ALTA PRODUCTOS - NOMBRE DEL ALUMNO</H1>
<?PHP
INCLUDE "conexion.php";


/* SE MUESTRA EL FORMULARIO LA PRIMERA VEZ */
IF (!ISSET($_POST) || EMPTY($_POST)) { 

	$CATEGORIAS = OBTENERCATEGORIAS($db);
	
    /* SE INICIALIZA LA LISTA VALORES*/
	ECHO '<FORM ACTION="" METHOD="POST">';
?>
<DIV CLASS="CONTAINER ">
<!--APLICACION-->
<DIV CLASS="CARD BORDER-SUCCESS MB-3" STYLE="MAX-WIDTH: 30REM;">
<DIV CLASS="CARD-HEADER">DATOS PRODUCTO</DIV>
<DIV CLASS="CARD-BODY">
		<DIV CLASS="FORM-GROUP">
        ID PRODUCTO <INPUT TYPE="TEXT" NAME="IDPRODUCTO" PLACEHOLDER="IDPRODUCTO" CLASS="FORM-CONTROL">
        </DIV>
		<DIV CLASS="FORM-GROUP">
        NOMBRE PRODUCTO <INPUT TYPE="TEXT" NAME="NOMBRE" PLACEHOLDER="NOMBRE" CLASS="FORM-CONTROL">
        </DIV>
		<DIV CLASS="FORM-GROUP">
        PRECIO PRODUCTO <INPUT TYPE="TEXT" NAME="PRECIO" PLACEHOLDER="PRECIO" CLASS="FORM-CONTROL">
        </DIV>
	<DIV CLASS="FORM-GROUP">
	<LABEL FOR="CATEGORIA">CATEGORÍAS:</LABEL>
	<SELECT NAME="CATEGORIA">
		<?PHP FOREACH($CATEGORIAS AS $CATEGORIA) : ?>
			<OPTION> <?PHP ECHO $CATEGORIA ?> </OPTION>
		<?PHP ENDFOREACH; ?>
	</SELECT>
	</DIV>
	</BR>
<?PHP
	ECHO '<DIV><INPUT TYPE="SUBMIT" VALUE="ALTA PRODUCTO"></DIV>
	</FORM>';
} ELSE { 
	$ID=$_POST['IDPRODUCTO'];
	$N=$_POST['NOMBRE'];
	$P=$_POST['PRECIO'];
	$CAT=$_POST['CATEGORIAS'];
	CREARPRODUCTO($db,$N,$P,$ID,$CAT);
}
?>

<?PHP

FUNCTION OBTENERCATEGORIAS($db) {
		$CATEGORIAS = ARRAY();
	
		$SQL = "SELECT ID_CATEGORIA, NOMBRE FROM CATEGORIA";
	
		$RESULTADO = MYSQLI_QUERY($db, $SQL);
		IF ($RESULTADO) {
			WHILE ($ROW = MYSQLI_FETCH_ASSOC($RESULTADO)) {
				$CATEGORIAS[] = $ROW['NOMBRE'];
			}
		}
		RETURN $CATEGORIAS;
	}
	FUNCTION CREARPRODUCTO($db,$N,$P,$ID,$CAT){
		$SQL = "SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='$CAT'";
		$RESULTADO = MYSQLI_QUERY($db,$SQL);
		IF ($RESULTADO){
			$ROW = MYSQLI_FETCH_ASSOC($RESULTADO);
			$SQL1 = "INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, PRECIO, ID_CATEGORIA) VALUES ('$ID','$N',$P,'".$ROW['ID_CATEGORIA']."')";
			MYSQLI_QUERY($db, $SQL1);
		}
	}

?>



</BODY>

</HTML>
